### ISSUE TITLE
Crashing very often.

### ISSUE THREAD

**Issue by CodingArctic-zz** [SteveKunG/SkyBlockcatia#1]
I get crashes with the below error when I clicked on someone's name in chat to open their profile, when I press B on any item, and some other situations that I'm forgetting now.

`The game crashed whilst updating screen events
Error: java.lang.NoSuchMethodError: net.minecraft.client.gui.inventory.GuiContainer.getSlotUnderMouse()Lnet/minecraft/inventory/Slot;`

**Comment by SteveKunG** [comment]
Can you send full crash log? it seems you downloaded the deobf jar.

**Comment by CodingArctic-zz** [comment]
[latest.log](https://github.com/SteveKunG/SkyBlockcatia/files/4969853/latest.log)
here's my latest.log

**Comment by SteveKunG** [comment]
Maybe try to remove mod one by one? I see the weird log appeared.
`Applying AsmWriter InjectWriter{className=net/minecraft/client/gui/GuiScreen, methodName=handleMouseInput, methodDesc=()V, at=At(value=me.falsehonesty.asmhelper.dsl.InjectionPoint$INVOKE@3456558, before=true, shift=0)} to class net.minecraft.client.gui.GuiScreen`

**Comment by CodingArctic-zz** [comment]
this only started happening when I added your mod so it's not any of mine

**Comment by SteveKunG** [comment]
A lot of people getting this, Please send your mods folder. Dm me on discord.

**Comment by SteveKunG** [comment]
Or updating to 1.0.1 should fix the issue.
