### ISSUE TITLE
Can't hide armor glint that supposed to hide it

### ISSUE THREAD

**Issue by RichterYT** [SteveKunG/SkyBlockcatia#10]
Hypixel make some item hide the enchanted glint

**Comment by SteveKunG** [comment]
Which one?

**Comment by NopoTheGamer** [comment]
dungeons armour and runes shouldn't have an enchant glint but they do an option to turn this off would be nice

**Comment by SteveKunG** [comment]
Glint for skulls already has config, but not for Dungeon Armor like Adaptive.
And this is hypixel fault. Armor that have an enchantment should render glint effect.
