### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by IssaFR1** [SteveKunG/SkyBlockcatia#11]
Hi ,my game is crashing Because of your mod ,so i cant play with it anymore :/ here's the crash report and i hope it get fixed (you may think its not skyblockcatia that crashs minecraft but it is)
[crash-2020-08-21_23.03.18-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/5111583/crash-2020-08-21_23.03.18-client.txt)

**Comment by SteveKunG** [comment]
Try remove patcher.

**Comment by IssaFR1** [comment]
> Try remove patcher.

Its not patcher ,its either SkyblockPlus or Danker's Skyblock Mod
EDIT : Yeah SkyblockCatia doesnt work with Danker's Skyblock Mod ,if this could be fixed i will be very happy ^^
If you cant fix u can just put Danker's Skyblock Mod in the incompatible mods list ,have a nice day
EDIT 2 : So its not these mods that crashs mc ,weird ... still investigating
EDIT 3 : The option "Skin rendering fix" makes mc crashs but all the entites are invisible ,Dankers mod doesnt work with sbcatia
EDIT 4 : Without "patcher" ,"sb+" and "danker's mod" and skin rendering fix enabled, it doesnt crash but all the entites are invisible :/

**Comment by IssaFR1** [comment]
well forget it for some reason my mc works again ,ty ^^
