### ISSUE TITLE
Crash and ...

### ISSUE THREAD

**Issue by Rokuyon-tokyo** [SteveKunG/SkyBlockcatia#13]
A crash when returning from the API viewer.
When this mod is put in, VOXELMAP will be disabled.
Is it possible to display all RenderInfo on the left?
I would like to be able to move the location of the GUI like SkyBlockAddons.
[crash-2020-08-31_15.13.50-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/5148665/crash-2020-08-31_15.13.50-client.txt)

**Comment by SteveKunG** [comment]
I think `pluckymod, melodymod or intelliinput` might caused the issues.
