### ISSUE TITLE
Add option for 24 hours time format

### ISSUE THREAD

**Issue by jkroepke** [SteveKunG/SkyBlockcatia#14]
Hi,

please add an option to support 24 hour time format (e.g in render info) instead the 12 hour AM/PM time format.

For example in Germany we have the 24 hour time format but we often prefer an english game language. 

Looking at the code, the locale date format is used.
https://github.com/SteveKunG/SkyBlockcatia/blob/c41787a4dd1ed9471f2b80791c0b0d1e3bd2f49b/src/main/java/com/stevekung/skyblockcatia/renderer/HUDInfo.java#L190-L191

Maybe it possible to define a custom date format (using the [date/time letters](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)) inside the options would be the best.

Thanks.

Great mod btw!

**Comment by SteveKunG** [comment]
Fixed in 1.0.9
