### ISSUE TITLE
Crash with club.sk1er ModCore 0.1.42 (required by Patcher) java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by jkroepke** [SteveKunG/SkyBlockcatia#15]
Hi,

my game crash if I update club.sk1er ModCore to 0.1.42. With 0.1.41 it's fine. It looks like can conflict between the ClassTransformations.

https://paste.ee/p/hYgL6

**Comment by SteveKunG** [comment]
This doesn't occured to me, Did you try the latest patcher 1.3?

**Comment by jkroepke** [comment]
For unknown reason, I didn't have this error any more.
