### ISSUE TITLE
Rarity items dont work

### ISSUE THREAD

**Issue by SnrSterling** [SteveKunG/SkyBlockcatia#16]
The rarity of things does not want to be shown. The language changed to English everywhere. Both in the profile and in the game.
Screen: https://i.imgur.com/lMhi3L5.png
What else can you try to do?
Version mod: **SkyBlockcatia-1.8.9-inv-fix.jar**
Modlist: https://i.imgur.com/ff24VAX.png
Resource Packs:  https://i.imgur.com/iu85bAn.png

**Comment by SteveKunG** [comment]
Fixed in 1.0.9
