### ISSUE TITLE
Mods that allow the player to hide scoreboard dont work.

### ISSUE THREAD

**Issue by ThatGravyBoat** [SteveKunG/SkyBlockcatia#19]
https://github.com/SteveKunG/SkyBlockcatia/blob/e51212d95349ec828a3e7d74eb3529c1d9be0fba/src/main/java/com/stevekung/skyblockcatia/event/HUDRenderEventHandler.java#L119
mods that allow the player to hide the scoreboard dont work because of this line above only accounting for mc debug info setting.

**Comment by SteveKunG** [comment]
Fixed in next release, Thanks!
