### ISSUE TITLE
None of the features work anymore

### ISSUE THREAD

**Issue by NotUnfriendingU** [SteveKunG/SkyBlockcatia#21]
I've been using this mod for about 3-4 weeks and all of the sudden, all my settings and stuff is gone. I can't use anything in the mod besides /sbapi (to view profiles) and /skyblockcatia gui (to edit the gui and stuff) plz help I wanna use this mod again!

**Comment by SteveKunG** [comment]
Crash or something? Or did you ever try only with my mod?
