### ISSUE TITLE
Support multiple rarity languages

### ISSUE THREAD

**Issue by jkroepke** [SteveKunG/SkyBlockcatia#22]
Hi,

currently item rarity overlay just work in english language.

https://github.com/SteveKunG/SkyBlockcatia/blob/310b9505e6d0d3a00cf5e1fe2f3d55c27e57faac/src/main/java/com/stevekung/skyblockcatia/utils/RenderUtils.java#L112

In Actions House some items has a rarity in different languages results that the rarity wont work. 

Maybe you could move away from word matching and just use a match based on the color.

**Comment by SteveKunG** [comment]
Well, Hypixel should export their API by default language (English). That's really annoying for website or mods.

**Comment by SteveKunG** [comment]
Fixed in 1.0.9
