### ISSUE TITLE
Extreme framedrops anywhere on hypixel

### ISSUE THREAD

**Issue by TheOnlyPhoenix** [SteveKunG/SkyBlockcatia#23]
Anywhere on hypixel, any lobby, any game, there are extreme framedrops. Like, to the point of 1 fps. It gets worse with a lot of particles, like emerald generators in BedWars, where the game completely freezes. As soon as i remove the mod, no framedrops. I really like this mod, but i literally cannot play the game with it...

**Comment by SteveKunG** [comment]
Fixed in 1.0.9
