### ISSUE TITLE
The buttons on side right side not working

### ISSUE THREAD

**Issue by jkroepke** [SteveKunG/SkyBlockcatia#26]
Hi,

the button on the right side are not working while the buttons inside player inventory works fine.

![image](https://user-images.githubusercontent.com/1560587/96367839-7735c300-1150-11eb-8ae2-4ee05bc14f72.png)

How I could identify the issue?

**Comment by SteveKunG** [comment]
Some people reported to me it was caused by latest NEU, Not sure wtf are they doing with GuiScreen Event.

**Comment by jkroepke** [comment]
To be clarify: the was broken before I used NEU 1.4.

**Comment by SteveKunG** [comment]
1.3.1 is fine.

**Comment by jkroepke** [comment]
I feels like so. It wont work since after upgrade to 1.3.4 but I cant remember 100%

**Comment by Devviedehm** [comment]
For me, the buttons work _only when I press their top-left corner_. The ones that show up in the regular inventory, under the 2x2 crafting table, seem to work normally.

EDIT: I'd guess if there's any changes made to the GUI by other mods, it's probably something to do with the width/height settings for clicking (and maybe also what GUI scale is being used as well? e.g. differences between Small, Medium, Large, Auto).

**Comment by jkroepke** [comment]
https://github.com/Moulberry/NotEnoughUpdates/releases/tag/1.5-REL(3)

> Fixes
> * Fixed incompatiblity with SBC buttons

The issue is gone with thr 1.5 release.
