### ISSUE TITLE
Game crashes as soon as i finishes loading

### ISSUE THREAD

**Issue by yavko** [SteveKunG/SkyBlockcatia#28]
This only happens when I use the mod here

I have patcher 1.3 with font optimization off too

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (Skypixel-0.0.6(1).jar)
  FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  PopupEventsTweaker (Popup Events-1.3.1 (1.8.9) (1).jar)
  TNTTimerTweaker (TNT Time-1.0 (1.8.9).jar)
  CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.4-for-MC-1.8.9.jar)
  AutoCorrectTweaker (Autocorrect-1.2 (1.8.9) (1).jar)
  FMLLoadingPlugin (OofMod-2.0.2 (1.8.9) (1).jar)
  FMLLoadingPlugin (20 20 20-1.3 (1.8.9).jar)
  BossbarTweaker (Bossbar Customizer-1.1 (1.8.9) (1).jar)
  ModTweaker (Patcher-1.3 (1.8.9).jar)
  LabyModCoreMod (LabyMod-3.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9) (1).jar)
  FMLLoadingPlugin (LobbySounds-1.3 (1.8.9).jar)
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0 (1).jar)
  FMLLoadingPlugin (Sound Subtitles-1.1 (1.8.9).jar)
  FMLLoadingPlugin (Levelhead-7.1.2 (1.8.9).jar)
  RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  Glint Colorizer ([1.8.9] Glint Colorizer 1.0.jar)
  FMLLoadingPlugin (AutoGL-1.0 (1.8.9) (1).jar)
  PatcherTweaker (Patcher-1.3 (1.8.9).jar)
  FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/23/20 3:31 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at PerspectiveMethods.inGameHasFocus(PerspectiveMethods.java:13)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1321)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 731432352 bytes (697 MB) / 1509949440 bytes (1440 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1855 Optifine OptiFine_1.8.9_HD_U_L5 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1855.jar) 
	U	Forge{11.15.1.1855} [Minecraft Forge] (forge-1.8.9-11.15.1.1855.jar) 
	U	Glint-Colorizer{1.0} [Glint Colorizer] (minecraft.jar) 
	U	RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) 
	U	smoothfontcore{1.8.9-1.15.1} [Smooth Font Core] (minecraft.jar) 
	U	level_head{7.1.2} [Sk1er Level Head] (minecraft.jar) 
	U	randompatches{1.12.2-1.22.1.7} [RandomPatches] (randompatches-1.12.2-1.22.1.7.jar) 
	U	autotip{3.0.1} [Autotip] (Autotip-3.0.1 [1.8-1.12.2] (1).jar) 
	U	20_20_20{1.3} [20 20 20] (20 20 20-1.3 (1.8.9).jar) 
	U	packdisplaymod{1.0} [Pack Display Mod] ([1.8.9] packdisplaymod(1).jar) 
	U	autogg{4.0.3} [AutoGG] (AutoGG-4.0.3 (1.8.9).jar) 
	U	Danker's Skyblock Mod{1.7} [Danker's Skyblock Mod] (1.8.9.Danker.s.Skyblock.Mod.-.1.7.jar) 
	U	autogl{1.0} [AutoGL] (AutoGL-1.0 (1.8.9) (1).jar) 
	U	BloodKillEffect{0.0.5-alpha.1} [Blood Kill Effect Mod] (Blood-Kill-Effect-Mod-1.8.9.jar) 
	U	bossbar_customizer{1.1} [BossbarCustomizer] (Bossbar Customizer-1.1 (1.8.9) (1).jar) 
	U	sk1er-bedwars_resource_display{1.0} [Bedwars Resource Display Mod] (Bedwars Resource Display-1.0 (1.8.9) (1).jar) 
	U	ChromaHUD{3.0} [Chroma HUD] (ChromaHUD-3.0 (1.8.9).jar) 
	U	combat_info{1.0} [Sk1er Combat Info Mod] (Combat Info-1.0 (1.8.9).jar) 
	U	fbp{2.4.1} [Fancy Block Particles] (FancyBlockParticles-1.8.9-2.4.1.jar) 
	U	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.3-law-1.8.x(1).jar) 
	U	hypixel_auto_complete{1.0} [Hypixel Autocomplete Mod] (Hypixel Autocomplete-1.0 (1.8.9) (1).jar) 
	U	keystrokesmod{8.0.2} [KeystrokesMod] (Keystrokes-8.0.2 (1.8.9).jar) 
	U	lobby_sounds{1.3} [Lobby Sounds] (LobbySounds-1.3 (1.8.9).jar) 
	U	BeezigForge{6.2.1} [Beezig Forge Expansion] (Beezig - The Hive Support.jar) 
	U	refractionoof{2.0.2} [OofMod] (OofMod-2.0.2 (1.8.9) (1).jar) 
	U	skyblockcatia{1.0.10} [SkyBlockcatia] (SkyBlockcatia-1.8.9-1.0.10.jar) 
	U	popup_events{1.3.1} [Popup Events] (Popup Events-1.3.1 (1.8.9) (1).jar) 
	U	ProjectL{0.2} [ProjectL] (ProjectL-0.2.jar) 
	U	quickplaypremium{1.0.4} [Quickplay Premium] (Quickplay Premium 1.8.9-1.0.4.jar) 
	U	text_overflow_scroll{1.2} [Scrollable Tooltips] (Scrollable Tooltips-1.2 (1.8.9) (1).jar) 
	U	quickplay{2.0.3} [Quickplay] (Quickplay-1.8.9-2.0.3.jar) 
	U	skypixel{0.0.6} [Skypixel] (Skypixel-0.0.6(1).jar) 
	U	subtitles_mod{1.1} [Backported Subtitles] (Sound Subtitles-1.1 (1.8.9).jar) 
	U	soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
	U	tnttime{1.0} [TNT Time] (TNT Time-1.0 (1.8.9).jar) 
	U	smoothfont{1.8.9-1.15.2} [Smooth Font] (SmoothFont-1.8.9-1.15.2.jar) 
	U	skyblockaddons{1.5.4} [SkyBlock Addons] (SkyblockAddons-1.5.4-for-MC-1.8.9.jar) 
	U	labymod{3.6.13} [LabyMod] (LabyMod-3.jar) 
	U	victory_royale{1.0} [Victory Royale Mod] (Victory Royale-1.0 (1.8.9) (1).jar) 
	U	enhancements{7.7} [Vanilla Enhancements] (Vanilla+Enhancements-7.7.jar) 
	U	notenoughupdates{1.4-REL} [NotEnoughUpdates] (NotEnoughUpdates-1.4.2-REL.jar) 
	U	patcher{1.3} [Patcher] (Patcher-1.3 (1.8.9).jar) 
	U	autocorrect{1.2} [AutoCorrect] (Autocorrect-1.2 (1.8.9) (1).jar) 
	U	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (Skypixel-0.0.6(1).jar)
  io.prplz.skypixel.asm.ClassTransformer
FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  
PopupEventsTweaker (Popup Events-1.3.1 (1.8.9) (1).jar)
  
TNTTimerTweaker (TNT Time-1.0 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.mods.tnttimer.tweaker.ClassTransformer
CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  bre.smoothfont.asm.Transformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.4-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
AutoCorrectTweaker (Autocorrect-1.2 (1.8.9) (1).jar)
  club.sk1er.autocorrect.tweaker.ClassTransformer
FMLLoadingPlugin (OofMod-2.0.2 (1.8.9) (1).jar)
  
FMLLoadingPlugin (20 20 20-1.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
BossbarTweaker (Bossbar Customizer-1.1 (1.8.9) (1).jar)
  club.sk1er.bossbarcustomizer.tweaker.ClassTransformer
ModTweaker (Patcher-1.3 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
LabyModCoreMod (LabyMod-3.jar)
  net.labymod.core.asm.LabyModTransformer
  net.labymod.addons.betterperspective.asm.PerspectiveTranformer
  net.labymod.addons.betterhat.asm.BetterHatTransformer
  net.labymod.addons.custommainmenu.asm.CustomMainMenuTransformer
  org.burgerbude.labymod.addons.glintcolorizer.GlintColorizerTransformer
  dev.rocco.laby.tabcomplete.asm.TabTransformer
  net.labymod.addons.itemphysic.asm.ItemPhysicTransformer
  net.labymod.addons.moreparticle.asm.MoreParticleTranformer
  net.labymod.addons.resourcepacks24.asm.Resourcepacks24Transformer
  net.labymod.addons.shinypots.asm.ShinyPotsTranformer
FMLLoadingPlugin (Scrollable Tooltips-1.2 (1.8.9) (1).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
FMLLoadingPlugin (LobbySounds-1.3 (1.8.9).jar)
  
RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0 (1).jar)
  api.player.forge.RenderPlayerAPITransformer
FMLLoadingPlugin (Sound Subtitles-1.1 (1.8.9).jar)
  
FMLLoadingPlugin (Levelhead-7.1.2 (1.8.9).jar)
  club.sk1er.mods.levelhead.forge.transform.ClassTransformer
RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Glint Colorizer ([1.8.9] Glint Colorizer 1.0.jar)
  me.powns.glintcolorizer.asm.itemrender.RenderItemTransformer
FMLLoadingPlugin (AutoGL-1.0 (1.8.9) (1).jar)
  
PatcherTweaker (Patcher-1.3 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6344' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1855
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 24.20.100.6344, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.8.zip (incompatible), skyblock/v12F32x_Skyblock_Pack_1.8.9.zip (incompatible), FaithfulTweaks_6SU1A2343S.zip (incompatible), Faithful+3D+-+1.8+r-1.zip (incompatible), Faithful+Dark+UI+1.15.2.zip (incompatible), Outlined Ores Addon for Faithful.zip (incompatible), alternate-entities-v1-2.zip (incompatible), Round+Trees+2.8+§31.8+§o (1).zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6344
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by SteveKunG** [comment]
Caused by `at PerspectiveMethods.inGameHasFocus(PerspectiveMethods.java:13)`

**Comment by yavko** [comment]
this ONLY happens with this mod!!!! Not any of mine I have tested this a lot it isn't any other mod but yours.

**Comment by SteveKunG** [comment]
How then, My mod doesn't do anything with perspective. Did you see any mixins conflict in the log?
