### ISSUE TITLE
Error message when attempting to view Api

### ISSUE THREAD

**Issue by Drillox** [SteveKunG/SkyBlockcatia#30]
![image](https://user-images.githubusercontent.com/73443861/97117799-fd787900-16fd-11eb-9057-bd56282b720c.png)
This error message pops up and only happens when I try to view the most recently active profile, or the one that is highlighted in yellow. 
![image](https://user-images.githubusercontent.com/73443861/97117873-6c55d200-16fe-11eb-9c45-74d9e9a1a0a9.png)
Here are the mods that I'm using in combination with Skyblock catia, incase there is something done wrong on my end

**Comment by SteveKunG** [comment]
Fixed in 1.0.11
