### ISSUE TITLE
[Enhancement] Chat Mode display - update with commands

### ISSUE THREAD

**Issue by Devviedehm** [SteveKunG/SkyBlockcatia#31]
Currently Chat Mode only changes the displayed mode when it's switched with the buttons on the right-side of the screen.

I would like it if using /chat g and /chat a commands manually would also update it, either as it sends or by checking received messages to check for "You are now in GUILD chat!", for example.

Additionally, though at much lower priority, a few more improvements to this functionality:

- add Chat Mode to quick config menus - currently only "hidden" in the default "main config", inside the Forge config screens
- configure the buttons (position, color), or at least move them to the left side so they are more noticeable next to the Chat Mode box display
- keybind to rotate through chat modes, and/or keybinds to switch to a specific one

Current Layout:
![image](https://user-images.githubusercontent.com/14819307/97382269-e3d45e80-18c2-11eb-9f94-07d6ef6cb17d.png)

Suggested Layout:
![image](https://user-images.githubusercontent.com/14819307/97382302-f2227a80-18c2-11eb-94dc-996bf03ef0d4.png)

**Comment by SteveKunG** [comment]
Thanks but this feature has been removed, because its a part of Indicatia.
I think there is a mod that you can select tab to chat, but I can't remember mod name.
