### ISSUE TITLE
The buttons under the 2x2 crafting grid doesn't work, but if i hover my mouse over my avatar, the words appear, but you cant click it

### ISSUE THREAD

**Issue by Sharkily** [SteveKunG/SkyBlockcatia#32]
The buttons under the 2x2 crafting grid doesn't work, but if i hover my mouse over my avatar, the words appear, but you cant click it

**Comment by SteveKunG** [comment]
Fixed in NEU. https://github.com/Moulberry/NotEnoughUpdates/releases/tag/1.5.1-REL
