### ISSUE TITLE
Fishing Rod line override causing issues where other mods.

### ISSUE THREAD

**Issue by ThatGravyBoat** [SteveKunG/SkyBlockcatia#33]
Can you please change your [RenderFishMixin ](https://github.com/SteveKunG/SkyBlockcatia/blob/1.8.9/src/main/java/com/stevekung/skyblockcatia/mixin/RenderFishMixin.java)to do something similar to how its being done in NotEnoughUpdates where its injected at the front and if the conditions are meet it will cancel the method meaning it will cancel the vanilla method but not your injected method and will run your code for rendering you can see an example of this here. [https://github.com/Moulberry/NotEnoughUpdates/blob/beta/src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinRenderFish.java](https://github.com/Moulberry/NotEnoughUpdates/blob/beta/src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinRenderFish.java) This change will allow players to use such features as the coloured fishing rod lines which is in NEU, I just hate to see players not getting the full experience of mods because of incompatibilities. Thanks for reading and I hope this change can be added!

**Comment by SteveKunG** [comment]
Yeah it was my own private mod before, so removed it all should solve all issues. :D
Fixed in https://github.com/SteveKunG/SkyBlockcatia/commit/0e4834f2d9863a58f1117e26129bb37e30e5e581

**Comment by SteveKunG** [comment]
You can also get experimental build in my discord : https://discord.gg/54VqgZb

**Comment by SteveKunG** [comment]
Fixed in 1.0.13.
