### ISSUE TITLE
How do I disable the dragon hitbox?

### ISSUE THREAD

**Issue by Olerix** [SteveKunG/SkyBlockcatia#37]
Hello. I apologize right away for my poor knowledge of the English language. I'm from Russia. I would like to ask a question. Your mod has the "Show only dragon hitbox" and "Show hitbox when dragon spawned" functions. If you enable these functions, then we will show the hitbox of the dragon and the hitbox of the dragon crystals. I would like to have only the crystal hitbox shown. Is it possible to configure this somewhere? Maybe you know the path in your mod to this setting?

**Comment by SteveKunG** [comment]
Added config in 1.0.13, You can choose what should be rendered hitbox in the end.
