### ISSUE TITLE
Disabling item rarity

### ISSUE THREAD

**Issue by Paultje52** [SteveKunG/SkyBlockcatia#39]
Hello. How can I disable the background rarity color?
![image](https://user-images.githubusercontent.com/31313717/101288265-f745e400-37f5-11eb-8768-82ce76be5861.png)

**Comment by SJKZ1-2565** [comment]
F4 > skyblock setting > rendering > show item rarity

**Comment by SJKZ1-2565** [comment]
> Hello. How can I disable the background rarity color?
> ![image](https://user-images.githubusercontent.com/31313717/101288265-f745e400-37f5-11eb-8768-82ce76be5861.png)
F4 > skyblock setting > rendering > show item rarity
