### ISSUE TITLE
Highly Frequent Framedrops, Time Outs and Server Crashes Makes the Game Borderline Unplayable.

### ISSUE THREAD

**Issue by Alucaius** [SteveKunG/SkyBlockcatia#40]
The problem is very simple, almost everywhere on Hypixel including Skyblock there are very frequent frame drops or freezes. This occurs in lobbies where player counts are high or as low as only one person. It doesn't happen with any other mod. This appears to be the same problem as [Issue #23](https://github.com/SteveKunG/SkyBlockcatia/issues/23). Even though that was closed because It was fixed in 1.0.9, it still happens in 1.0.12.

Here is a list of the mods I generally use with Skyblockcatia
![8-12-2020 modlist](https://user-images.githubusercontent.com/74951027/101461130-86184500-394b-11eb-919d-ff9a763e885f.png)

**Comment by SteveKunG** [comment]
Not really sure what's causing this again, Try to remove BetterFPS and foamfix? Because you already have Patcher.

**Comment by Alucaius** [comment]
Tried removing BetterFPS, FoamFix and Patcher. Nothing changed.

**Comment by SteveKunG** [comment]
Or you could zip your mods folder and send it to me. DM on discord then.

**Comment by mpfaff** [comment]
I've noticed serious performance issues with SkyblockAddons. Have you tried disabling it?

**Comment by IssaFR1** [comment]
ik that neu makes performances issues ,for me it shreds my fps when i open inventory with neu (even with cache item pane option enabled)

**Comment by Alucaius** [comment]
I have had all of those mods for a very long time and only just recently added Skyblockcatia; personally, no doubt It was causing the performance issues. The good thing is it doesn't happen anymore on 1.0.14
