### ISSUE TITLE
game does not launch on the latest update

### ISSUE THREAD

**Issue by chaitanya-codes** [SteveKunG/SkyBlockcatia#41]
when I click Play, the launcher closes but nothing opens. this doesn't happen with the previous version (1.0.12) but when I use 1.0.13 my game just won't launch

**Comment by SteveKunG** [comment]
Crash report?

**Comment by chaitanya-codes** [comment]
No crash report was generated. The javaw process runs as I see in task manager but it does not show

**Comment by Upgradingmaster** [comment]
I experience the same issue. The game doesn't crash it runs as it is supposed to but the game window is not open and is only open in the background tasks section/ details section.

**Comment by SteveKunG** [comment]
Then send the "latest.log"

**Comment by javigines** [comment]
Here you go
[latest.log](https://github.com/SteveKunG/SkyBlockcatia/files/5659259/latest.log)

I have done some test and the mods that crash are PlayerAPI and the new version. Player API is needed because some mods doesn't like some override optifine does to work. It's deprecated but is the recommend mod to solve the problem, and it works with the 1.0.12 of your mod.

**Comment by SteveKunG** [comment]
**sigh**, I hate to deal with outdated mod.
I saw Player API replace the whole EntityPlayerSP class -.-

**Comment by SteveKunG** [comment]
Please test with the experimental build, you can get it on my discord.

**Comment by Upgradingmaster** [comment]
it works now with the experimental build, thanks!

**Comment by javigines** [comment]
Works great now! Good job.

**Comment by Upgradingmaster** [comment]
sorry if this is an unrelated bug but when I try to see the bazaar price on the tooltips it says that the config is empty?
![image](https://user-images.githubusercontent.com/70477893/101491006-9bf22e00-397c-11eb-9de6-88edc46d5bfe.png)

**Comment by SteveKunG** [comment]
@Upgradingmaster You need an API Key for viewing bazaar data, my bad.
