### ISSUE TITLE
Game not launching when using SkyBlockcatia

### ISSUE THREAD

**Issue by Concxpts** [SteveKunG/SkyBlockcatia#43]
This mod is important for the ULTIMATE SkyBlock experience and uhh... this mod doesn't allow minecraft to launch when it's in my mods folder. It will say that minecraft is already open when trying to launch again but uh haha no

**Comment by SteveKunG** [comment]
Check out experimental build in my discord and try it.

**Comment by Concxpts** [comment]
Thank you my kindest sir

**Comment by SteveKunG** [comment]
Please try with official 1.0.14
