### ISSUE TITLE
Dont work some functions in mod.

### ISSUE THREAD

**Issue by SnrSterling** [SteveKunG/SkyBlockcatia#44]
Hello. Mod functions do not work. What to do?
Item Rarity: https://i.imgur.com/Dr1u5Q0.png and https://i.imgur.com/sJwBTQ6.png
Dont work and  Toast Notifications, Auction BIDS Overlay

# Mods Loaded
[Minecraft Coder Pack][minecraft.jar]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar]
[ModCore][Sk1er Modcore-0.1.47 (1.8.9).jar]
[Fullbright][1.8.9-Fullbright-v1.2.1.jar]
[ChatTriggers][ctjs-1.3.0-1.8.9.jar]
[NotEnoughUpdates][NotEnoughUpdates-1.7.2-REL.jar]
[Patcher][Patcher-1.4.1 (1.8.9).jar]
[Scrollable Tooltips][Scrollable Tooltips-1.3 (1.8.9).jar]
[SkyBlock Addons][SkyblockAddons-1.5.4-for-MC-1.8.9.jar]
[SkyBlockcatia][SkyBlockcatia-1.8.9-1.0.13.jar]

**Comment by SteveKunG** [comment]
Send "latest.log" please.

**Comment by SnrSterling** [comment]
Problem was in **LiteLoader** 
![image](https://user-images.githubusercontent.com/28922962/101618293-dadabf00-3a22-11eb-88c6-d9e8d4292510.png)
