### ISSUE TITLE
Skyblockcatia bug

### ISSUE THREAD

**Issue by wlhelm** [SteveKunG/SkyBlockcatia#49]
When im walking backwards pressing s, i walk normally backwards. But the second i press control, i stop moving backwards while still pressing s. Ive tested the mod, without any other mods of folders in my mods folder, and the bug still happens.

**Comment by SJKZ1-2565** [comment]
ctrl + s = toggle sprin if you don't like it just disable it

**Comment by SteveKunG** [comment]
Or you just disable movement handler in global config, that behavior is prevent player move backward while enabled/disabled toggle sprint.
