### ISSUE TITLE
Skyblockcatia not letting game launch

### ISSUE THREAD

**Issue by CosmikPandaz** [SteveKunG/SkyBlockcatia#50]
I tried launching the game and it doesn't work with skyblock catia in the mod folder, if I remove it everything works fine. When i launch it i get this message(image attached) and i put a list of mods i use. 

Forge Mod Loader has found a problem with your Minecraft installation the mods and versions listed below could not be found 
Forge : minimum version required is 11.15.1.2318 The file 'logs/fml-client-latest.log' contains more information
![Minecraft](https://user-images.githubusercontent.com/48935589/102381863-99946300-3f7e-11eb-929f-52353c045e18.PNG)

![ModList](https://user-images.githubusercontent.com/48935589/102381733-6d78e200-3f7e-11eb-8a79-f299e7486767.PNG)

**Comment by SteveKunG** [comment]
-.-
did you actually read that messages on your screen?
If not, update forge to latest 1.8.9.

**Comment by CosmikPandaz** [comment]
I did install the latest version and this still happens

**Comment by SteveKunG** [comment]
I'm pretty sure you selected wrong forge version in the launcher.
