### ISSUE TITLE
Forge not starting with skyblockatia in the mods folder

### ISSUE THREAD

**Issue by NotNvS** [SteveKunG/SkyBlockcatia#51]
i

**Comment by Devviedehm** [comment]
Update SBA to 1.5.4. If you still have problems, please provide more info. Ideally a list of mods and the file .minecraft\logs\latest.log or at least the last few lines of it right after a crash.

**Comment by SteveKunG** [comment]
@Devviedehm Thank you for help! I'm really appreciated!
