### ISSUE TITLE
Minecraft wont start at all with Skyblockcatia ver 1.0.13-1.0.15 for 1.8.9

### ISSUE THREAD

**Issue by Nackoy** [SteveKunG/SkyBlockcatia#53]
The only error message I get, I have the newest forge version for 1.8.9 and latest java version
![Screenshot 2020-12-19 201517](https://user-images.githubusercontent.com/76270398/102703051-0d14c980-4238-11eb-91f6-32e2f0b38d34.png)
The mods I have installed along with it. None of the mods I have cause problems with each other that i know of
![modlist](https://user-images.githubusercontent.com/76270398/102703064-3a617780-4238-11eb-8ae1-f04ba6cc7b2e.png)
**Version 1.0.12 works perfectly, but anything higher doesnt**

**Comment by Devviedehm** [comment]
You might want to upload the "latest.log" file from your .minecraft\logs\ folder as well, or at least share the part where it lists what crashed and what called the part that crashed. It should usually be the last few lines in the file after a crash.

From your mod list though, you might want to remove Mouse Delay FIX (included in one of the options in Patcher), update Patcher (version 1.4.1 is out, and there's betas for version 1.5), remove ToggleSneak and ToggleSprint if you can get SkyBlockcatia to boot again (you have the "/skyblockcatia toggle_sneak enable" command if you enable SkyBlockcatia's Movement Handler in the Mods list, global config options, and can bind it to a key as well).

You might also want to update OptiFine to one of the preview versions that fix a few of the bugs (there's L6 pre1 and M5 pre2 at the moment).

I'm not sure if PlayerAPI is used by any other mod, and you should have /pv <player> with, I think, SBA or NEU.

I've also seen people report problems with AutoGG.

**Comment by Nackoy** [comment]
Thank you! I updated my Optifine, and updated/removed the mods you mentioned, and is now working with the new versions.
