### ISSUE TITLE
Crashes upon opening skyblock

### ISSUE THREAD

**Issue by Prequx** [SteveKunG/SkyBlockcatia#57]
It works fine until I load up hypixel and I try to get on my skyblock then it crashes. 
[Crashers.txt](https://github.com/SteveKunG/SkyBlockcatia/files/5784342/Crashers.txt)

**Comment by SteveKunG** [comment]
Don't use latest SteveKunG's Lib, please stay in 4.0.1 until I drop a new release of SkyBlockcatia.
