### ISSUE TITLE
Main settings in mod

### ISSUE THREAD

**Issue by Prequx** [SteveKunG/SkyBlockcatia#58]
The mod works great and I'm loving it so far, but the default f4 key doesn't seem to work to open the main settings for the mod. There is also no option to change the binding in the controls as it doesn't seem to exist. Not urgent but I couldn't seem to find anyone else talking about it online so I thought I'd ask here. Thanks.

**Comment by SteveKunG** [comment]
It is 1.16.4? If yes there is no config support yet.

**Comment by SteveKunG** [comment]
Added config gui in 2.0.3.
