### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by manofthegod** [SteveKunG/SkyBlockcatia#59]
When I go on Hypixel and try to play Skyblock with this mod in 1.16.4 latest version it lets me go on Hypixel but when I try and play Skyblock it will crash I have SteveKungLib on to latest version I just crash when I try to play can you please fix it?

**Comment by SteveKunG** [comment]
Do not update SteveKunG's Lib, stay on 4.0.1.

**Comment by remplerus** [comment]
well it should work with PR #61

**Comment by manofthegod** [comment]
thx
