### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by Refluxer** [SteveKunG/SkyBlockcatia#6]
my game crashes even tho the mod it's be itself

**Comment by SteveKunG** [comment]
crash report?

**Comment by swickedman** [comment]
> отчет о катастрофе?

[crash-2020-08-15_09.50.06-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/5078333/crash-2020-08-15_09.50.06-client.txt)

mod crashes, here's the log

**Comment by boon4681** [comment]
Update forge to last version
http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html
