### ISSUE TITLE
Jungle Axe/Treecapitator Cooldown timer not showing up

### ISSUE THREAD

**Issue by goodmario1** [SteveKunG/SkyBlockcatia#63]
With new Hypixel Skyblock update the Jungle Axe/Treecapitator Cooldown timer no longer shows up on public islands. It seems to still work on my private island. MC version 1.8.9, SBC version 1.0.16.

**Comment by SteveKunG** [comment]
Seems to caused by hypixel new block breaking system. I'll figure out to fix this later since its all server side only....
