### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by UltraBlackLinux** [SteveKunG/SkyBlockcatia#64]
Hey, there
Since Patchworkmc will propably take a long time to reach 1.16 - What about a Fabric version of this? Just curious.
Thanks!

**Comment by SteveKunG** [comment]
Yeah, but architectury-api is a thing I wanted to make compatible with Forge/Fabric. I might port to use that soon.

**Comment by SteveKunG** [comment]
Fabric Version is out, please try it :)
https://www.curseforge.com/minecraft/mc-mods/skyblockcatia/files/3286376
