### ISSUE TITLE
Toasts Not Showing 1.8.9

### ISSUE THREAD

**Issue by PhoenixFlock** [SteveKunG/SkyBlockcatia#66]
I have reset the config in /skyblockcatia gui to the default config to try to resolve the problem but whenever i get allowance,pet lvl up,gifts the toast still does'nt show up i am using v1.0.16 and play on 1.8.9

**Comment by PhoenixFlock** [comment]
HELP ME! Plz

**Comment by PhoenixFlock** [comment]
I also have put in my api key

**Comment by SteveKunG** [comment]
Mod list? Toast should be work fine if some of mod don't break chat event.

**Comment by SteveKunG** [comment]
Closing due to inactive, I can't reproduce an issue with toast.
