### ISSUE TITLE
SkyblockCatia crash

### ISSUE THREAD

**Issue by CallMeDogo** [SteveKunG/SkyBlockcatia#68]
My game crashes when I open it with the SkyblockCatia mod, what can I do to solve this problem?

**Comment by SteveKunG** [comment]
Crash report please -.-

**Comment by CallMeDogo** [comment]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game
Exit Code: -1

**Comment by SteveKunG** [comment]
https://www.curseforge.com/minecraft/mc-mods/skyblockcatia/files/3178524
