### ISSUE TITLE
Can't start minecraft with Skyblockatia

### ISSUE THREAD

**Issue by Testoriven** [SteveKunG/SkyBlockcatia#7]
[crash-2020-08-16_14.23.41-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/5080634/crash-2020-08-16_14.23.41-client.txt)

newest forge, newest skyblockatia update i believe, can't get minecraft started with this mod loaded...

**Comment by SteveKunG** [comment]
Update SBA to 1.5.0
