### ISSUE TITLE
Sbapi inventory crashing on mouseover.

### ISSUE THREAD

**Issue by RectangularObject** [SteveKunG/SkyBlockcatia#72]
[crash-2021-02-28_16.04.51-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/6057958/crash-2021-02-28_16.04.51-client.txt)

The game crashes when I move my mouse over the inventory screen in the /sbapi command.

**Comment by SteveKunG** [comment]
This has been fixed in latest commit.
