### ISSUE TITLE
API Viewer doesn't work when used 2 times on a person.

### ISSUE THREAD

**Issue by SenkiDaKitty** [SteveKunG/SkyBlockcatia#75]
![image](https://user-images.githubusercontent.com/44231818/113476612-db3d1100-947c-11eb-8bdd-a170968e40d9.png)
This happens when you check a person, close the menu then check them again.
Even if you relog it won't allow you to view their profile.

**Comment by SteveKunG** [comment]
Fixed in https://github.com/SteveKunG/SkyBlockcatia/commit/b0103a8c9446a85f254eb77a5e068502b623cbfd
