### ISSUE TITLE
Crash on startup caused by SkyblockCatia

### ISSUE THREAD

**Issue by whitetxt** [SteveKunG/SkyBlockcatia#80]
I am experiencing a new crash on startup.
Removing SkyblockCatia from my mod folder fixes this issue.
[crash-2021-05-13_17.48.33-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/6473908/crash-2021-05-13_17.48.33-client.txt)

**Comment by SteveKunG** [comment]
https://discord.com/channels/356400329086205953/804380035946381372/842401955568812124

**Comment by whitetxt** [comment]
I can't see that

**Comment by SteveKunG** [comment]
Join my discord https://discord.gg/kQ8vaEAf
and go to #roles, then click that link.

**Comment by whitetxt** [comment]
Yep thats fixed it. Thanks.
