### ISSUE TITLE
Can't launch skyblock catia

### ISSUE THREAD

**Issue by Sventt** [SteveKunG/SkyBlockcatia#82]
Hey friend when I launch my version with the skyblockcatia 1.8.9 version it says an error related with forge and idk what other things, but when I remove your mod Minecraft launch correctly I hope you can fix that because I really like the glow color tiers of the items

**Comment by Sventt** [comment]
The version I was using is 1.1.2

**Comment by Sventt** [comment]
[skyblockcatia issue.txt](https://github.com/SteveKunG/SkyBlockcatia/files/6488357/skyblockcatia.issue.txt)

**Comment by Sventt** [comment]
Now I tried with 1.0.16 version But I couldn't make run 
![image](https://user-images.githubusercontent.com/58893063/118379762-30029a00-b59a-11eb-9d44-81e295a9460a.png) 

Here you have the mods that I have in my modpack, when I remove skyblockcatia all is good but when I add it, the launcher crash, I hope you can help me with that my friend

**Comment by jani270** [comment]
> Hey friend when I launch my version with the skyblockcatia 1.8.9 version it says an error related with forge and idk what other things, but when I remove your mod Minecraft launch correctly I hope you can fix that because I really like the glow color tiers of the items

Hi this is an Issue between NEU and SBC, join the SBC Discord get the SBC Role in #roles then go into #skyblockcatia-release and download the fixed version. If you don't want that, get Skytils for Rarity Background. Also, please update Block Overlay and Optifine.

**Comment by Sventt** [comment]
Thanks a lot my friend, the fixed neu version worked for me, and also I updated the optifine and block overlay as u say me, really really appreciate my dear friend
