### ISSUE TITLE
I just started getting this crash error after updating to latest release 1.8.9

### ISSUE THREAD

**Issue by Ahstig** [SteveKunG/SkyBlockcatia#83]
I Just updated NEU and SBC and whenever I try to open the game, the game crashes. The crash only happens when Skyblockcatia is in the mods folder and did not happen in the last version.

[crash-2021-05-24_14.10.33-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/6534240/crash-2021-05-24_14.10.33-client.txt)

**Comment by Ahstig** [comment]
This was not SBC's fault. The new version of NEU was the problem

**Comment by jani270** [comment]
> This was not SBC's fault. The new version of NEU was the problem

If you update your Mods please read notes. A Note on the NEU Discord clearly says that you need to update SBC to use the NEU Update.
