### ISSUE TITLE
Skyblockcatia not compatible with NEU

### ISSUE THREAD

**Issue by PhoenixFlock** [SteveKunG/SkyBlockcatia#84]
Moulberry says he has tried everything to fix the issue but he cannnot fix it
Can you make a NEU compatible version i think you just need to remove skull retexturing
I love both these mods and want to play with them
PLZ

**Comment by jani270** [comment]
> Moulberry says he has tried everything to fix the issue but he cannnot fix it
> Can you make a NEU compatible version i think you just need to remove skull retexturing
> I love both these mods and want to play with them
> PLZ

There is already a fix on the discord:

How to fix Skyblockcatia crash:

Step 1: Join the SkyBlockcatia Discord: https://discord.gg/6JhEjeY
Step 2: Go into #roles 
Step 3: React with :island:  (https://cdn.discordapp.com/attachments/659613194066722833/846716419282173952/unknown.png)
Step 4: Go into #skyblockcatia-release
Step 5: Download the fixed version and replace it with your old SBC file
