### ISSUE TITLE
Minecraft 1.16.5 Game crashed when starting

### ISSUE THREAD

**Issue by edremy-Ohagi** [SteveKunG/SkyBlockcatia#87]
These are my files when crashing
[Crash reports.zip](https://github.com/SteveKunG/SkyBlockcatia/files/6645678/Crash.reports.zip)

**Comment by edremy-Ohagi** [comment]
btw I use Fabric mod loader not forge

**Comment by SteveKunG** [comment]
~~Caused by null UUID~~, What launcher are you using?

**Comment by edremy-Ohagi** [comment]
PCL II Launcher
Will it be solved if I change a launcher?

**Comment by SteveKunG** [comment]
Yep, or just use regular minecraft launcher.
