### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by KnightEmperor** [SteveKunG/SkyBlockcatia#9]
I can't install the Resource Pack as long as I have this module enabled，my game will be crashed.

actually，i can  enable material packs before，but after I restart the game, it cant do that.

[crash-2020-08-19_21.01.08-client.txt](https://github.com/SteveKunG/SkyBlockcatia/files/5096548/crash-2020-08-19_21.01.08-client.txt)

**Comment by SteveKunG** [comment]
Try to remove mod one by one? there are mods that I never heard or use them before in your crash report.

**Comment by KnightEmperor** [comment]
i tried it，nothing help.
Once the mod is enabled also the  Resource Packs installed, the game crashes.
And  Enabling Resource Packs in the game will also crash

**Comment by KnightEmperor** [comment]
Because I am in China, it is difficult for us to load they are website from other countries.If I hadn't done network acceleration on the game（Reduce network latency）, I would have been unable to connect to the API and game will be crash.

My English is not very good, so I used a Google translate. Thank you for your make the mod

**Comment by SteveKunG** [comment]
Join my discord and go to #skyblockcatia channel, you can try the experimental build.
https://discord.gg/6JhEjeY
