### ISSUE TITLE
SkyBlockcatia is now incompatible with Patcher 1.6.

### ISSUE THREAD

**Issue by SuperDuggy117** [SteveKunG/SkyBlockcatia#94]
When SkyBlockcatia is run alongslide the new Patcher 1.6 release, the game crashes (presumably due to it's new Essential core).

**Comment by jani270** [comment]
> When SkyBlockcatia is run alongslide the new Patcher 1.6 release, the game crashes (presumably due to it's new Essential core).

Issue got fixed, you can find the fixed version on the [Discord](https://discord.gg/unz2YVb4)
