### ISSUE TITLE
My game insta-crashes while having this mod in my folder

### ISSUE THREAD

**Issue by Maratons4** [SteveKunG/SkyBlockcatia#98]
Crash report:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  TNTTimerTweaker (TNT Time-1.0 (1.8.9).jar)
  CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  FMLLoadingPlugin (Compact Chat-1.3 (1.8.9).jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  FMLLoadingPlugin (OofMod-3.0 (1.8.9).jar)
  FMLLoadingPlugin (MemoryFix-0.3.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-for-MC-1.8.9.jar)
  LoadingPlugin (Block_Overlay_4.0.3.jar)
  FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 21.3.10 10:10
Description: Initializing game

java.lang.NoClassDefFoundError: club/sk1er/patcher/hooks/FontRendererHook
	at net.minecraft.client.gui.FontRenderer.<init>(FontRenderer.java:168)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:427)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.FontRenderer.<init>(FontRenderer.java:168)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:427)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385771248 bytes (367 MB) / 973078528 bytes (928 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	U	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	U	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	U	refractionoof{3.0} [Oof Mod] (minecraft.jar) 
	U	smoothfontcore{1.8.9-1.15.1} [Smooth Font Core] (minecraft.jar) 
	U	autotip{3.0.1} [Autotip] (Autotip-3.0.1 [1.8-1.12.2].jar) 
	U	nick_hider{5.3.1} [Nick Hider] (Nick Hider-5.3.1 (1.8.9).jar) 
	U	replaymod{1.8.9-2.5.2} [Replay Mod] (replaymod-1.8.9-2.5.2.jar) 
	U	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	U	pownspotionhud{1.0} [pownspotionhud] (1.8.9_Powns_PotionEffect_HUD_-_1.0.jar) 
	U	Powns ArmorStatus HUD{1.0} [powns-armorhud] ([1.8.9] Powns ArmorStatus HUD - 1.1.jar) 
	U	pownscoordshud{1.0} [Powns' Coords HUD] ([1.8.9] Powns Coords HUD - 1.0.jar) 
	U	bspkrscore{1.8.9.2} [bspkrsCore] ([1.8.9]bspkrsCore-universal-1.8.9.2.jar) 
	U	sidebarmod{1.01} [SidebarMod] ([1.8.9]SidebarMod-1.01.jar) 
	U	autogg{4.0.3} [AutoGG] (AutoGG-4.0.3 (1.8.9).jar) 
	U	blockoverlay{4.0.3} [Block Overlay] (Block_Overlay_4.0.3.jar) 
	U	compactchat{1.3} [Compact Chat] (Compact Chat-1.3 (1.8.9).jar) 
	U	DiscordRP{1.2.4} [DiscordRP] (DiscordRP-1.2.4.jar) 
	U	dungeonrooms{3.2.4} [Dungeon Rooms Mod] (Dungeon_Rooms-3.2.4.jar) 
	U	hystats{2.0} [HyStats] (HyStats-v2.0 (1.8.9).jar) 
	U	keystrokesmod{8.0.2} [KeystrokesMod] (Keystrokes-8.0.2 (1.8.9).jar) 
	U	memoryfix{0.3} [MemoryFix] (MemoryFix-0.3.jar) 
	U	notenoughupdates{2.0.0-REL} [NotEnoughUpdates] (NotEnoughUpdates-2.0-PRE30.2.jar) 
	U	patcher{1.5.1} [Patcher] (Patcher-1.5.1 (1.8.9).jar) 
	U	quickplay{2.0.7} [Quickplay] (Quickplay-1.8.9-2.0.7.jar) 
	U	resourcepackmanager{1.0} [Resource Pack Manager] (Resource_Pack_Manager_1.1.jar) 
	U	text_overflow_scroll{1.3} [Scrollable Tooltips] (Scrollable Tooltips-1.3 (1.8.9).jar) 
	U	skyblockaddons{1.6.0} [SkyblockAddons] (SkyblockAddons-1.6.0-for-MC-1.8.9.jar) 
	U	skyblockcatia{1.3.2} [SkyBlockcatia] (SkyBlockcatia-1.8.9-1.3.2.jar) 
	U	SkyblockExtras{2.1.7.1} [SkyblockExtras] (SkyblockExtras-2.1.7.1.jar) 
	U	skyblockhud{1.13} [Skyblock Hud] (SkyblockHud-1.13-beta7.jar) 
	U	smoothfont{1.8.9-1.15.2} [Smooth Font] (SmoothFont-1.8.9-1.15.2.jar) 
	U	timechanger{2.1} [TimeChanger] (TimeChanger-2.2.1.jar) 
	U	tnttime{1.0} [TNT Time] (TNT Time-1.0 (1.8.9).jar) 
	U	sk1er_fullscreen{1.0} [Sk1er Fullscreen] (Windowed Fullscreen-1.0 (1.8.9).jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
TNTTimerTweaker (TNT Time-1.0 (1.8.9).jar)
  club.sk1er.mods.tnttimer.tweaker.ClassTransformer
CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  bre.smoothfont.asm.Transformer
FMLLoadingPlugin (Compact Chat-1.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (OofMod-3.0 (1.8.9).jar)
  us.nickfraction.oofmod.asm.EntityPlayerTransformer
  us.nickfraction.oofmod.asm.EntityArrowTransformer
  us.nickfraction.oofmod.asm.EntityFishHookTransformer
  us.nickfraction.oofmod.asm.RenderGlobalTransformer
FMLLoadingPlugin (MemoryFix-0.3.jar)
  io.prplz.memoryfix.ClassTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.6.0-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
LoadingPlugin (Block_Overlay_4.0.3.jar)
  me.aycy.blockoverlay.asm.Transformer
FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
  
ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
ItemPatchingLoader (ItemPhysic+Lite+1.3+mc1.8.9.jar)
  com.creativemd.itemphysic.ItemTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.49' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.49, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !  §f#§8Deep §bSky v2 §fRevamp.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.49
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by SteveKunG** [comment]
Update Patcher to 1.6.
